version: '3.7'
services:
  iam:
    container_name: iam_svc
    build: ./iam
    volumes:
      - ./iam:/usr/src/app
    ports:
      - 80:3000
    restart: always
    networks:
      kml_network:
        aliases:
          - iam_host
  events:
    container_name: events_svc
    build: ./eventsApi/eventsApi
    ports:
      - 4000:80
    restart: always
    networks:
      kml_network:
        aliases:
          - events_host
  mssql-server-linux:
    container_name: sql_server_svc
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "My_secret_p@ssword"
    ports:
      - "1433:1433"
networks:
  kml_network:
    name: kml_network_net
    driver: bridge
    ipam:
      driver: default