apiVersion :  app/v1
kind: Service
metadata:
  name: iam-lb
spec:
  type: LoadBalacer
  ports:
    - protocol: TCP
      port: 80




  replicas: 3
  selector:
    matchlabes:
      role: iam
  minReadySecond: 20
  strategy:
    rollingUpdate:
  template:
    metadata:
      labels:
        role: iam
    spect:
      containers:
      - name: iam
        image: adge/iam
        ports:
        - containerPort: 3800 